import { ROUTES } from '../constants/routes';

export const ROLE_NAVIGATION = {
  'Super Admin': [
    { path: ROUTES.DASHBOARD, label: 'Dashboard', iconName: 'IconDashboard' },
    { path: ROUTES.EMPLOYEES, label: 'Employees', iconName: 'IconUsers' },
    { path: ROUTES.DEPARTMENTS, label: 'Departments', iconName: 'IconFolder' },
    { path: ROUTES.DESIGNATIONS, label: 'Designations', iconName: 'IconBriefcase' },
    { path: ROUTES.ATTENDANCE, label: 'Attendance', iconName: 'IconCalendar' },
    { path: ROUTES.LEAVE, label: 'Leave', iconName: 'IconClock' },
    { path: ROUTES.REPORTS_ATTENDANCE, label: 'Attendance Reports', iconName: 'IconFileText' },
    { path: ROUTES.REPORTS_LEAVE, label: 'Leave Reports', iconName: 'IconFileText' },
    { path: ROUTES.REPORTS_RECRUITMENT, label: 'Recruitment Reports', iconName: 'IconFileText' },
    { path: ROUTES.JOBS, label: 'Job Openings', iconName: 'IconBriefcase' },
    { path: ROUTES.CANDIDATES, label: 'Candidates', iconName: 'IconUsers' },
    { path: ROUTES.INTERVIEWS, label: 'Interviews', iconName: 'IconCalendar' },
    { path: ROUTES.OFFER_LETTERS, label: 'Offer Letters', iconName: 'IconFileText' },
    { path: ROUTES.ONBOARDING, label: 'Onboarding', iconName: 'IconUsers' },
    { path: ROUTES.PAYROLL, label: 'Payroll', iconName: 'IconDollar' },
    { path: ROUTES.PERFORMANCE, label: 'Performance', iconName: 'IconTrendingUp' },
    { path: ROUTES.TRAINING, label: 'Training', iconName: 'IconBook' },
    { path: ROUTES.ASSETS, label: 'Assets', iconName: 'IconPackage' },
    { path: ROUTES.TIMESHEETS, label: 'Timesheets', iconName: 'IconClock' },
    { path: ROUTES.HELPDESK, label: 'Helpdesk', iconName: 'IconHelp' },
    { path: ROUTES.POLICIES, label: 'Policies', iconName: 'IconShield' },
    { path: ROUTES.DOCUMENTS, label: 'Documents', iconName: 'IconFolder' },
    { path: ROUTES.AUDIT_LOGS, label: 'Audit Logs', iconName: 'IconShield' },
    { path: ROUTES.SHIFTS, label: 'Shifts', iconName: 'IconClock' },
    { path: ROUTES.HOLIDAYS, label: 'Holidays', iconName: 'IconCalendar' },
  ],
  'HR Admin': [
    { path: ROUTES.DASHBOARD, label: 'Dashboard', iconName: 'IconDashboard' },
    { path: ROUTES.EMPLOYEES, label: 'Employees', iconName: 'IconUsers' },
    { path: ROUTES.DEPARTMENTS, label: 'Departments', iconName: 'IconFolder' },
    { path: ROUTES.DESIGNATIONS, label: 'Designations', iconName: 'IconBriefcase' },
    { path: ROUTES.ATTENDANCE, label: 'Attendance', iconName: 'IconCalendar' },
    { path: ROUTES.LEAVE, label: 'Leave', iconName: 'IconClock' },
    { path: ROUTES.REPORTS_ATTENDANCE, label: 'Attendance Reports', iconName: 'IconFileText' },
    { path: ROUTES.REPORTS_LEAVE, label: 'Leave Reports', iconName: 'IconFileText' },
    { path: ROUTES.REPORTS_RECRUITMENT, label: 'Recruitment Reports', iconName: 'IconFileText' },
    { path: ROUTES.JOBS, label: 'Job Openings', iconName: 'IconBriefcase' },
    { path: ROUTES.CANDIDATES, label: 'Candidates', iconName: 'IconUsers' },
    { path: ROUTES.INTERVIEWS, label: 'Interviews', iconName: 'IconCalendar' },
    { path: ROUTES.OFFER_LETTERS, label: 'Offer Letters', iconName: 'IconFileText' },
    { path: ROUTES.ONBOARDING, label: 'Onboarding', iconName: 'IconUsers' },
    { path: ROUTES.PERFORMANCE, label: 'Performance', iconName: 'IconTrendingUp' },
    { path: ROUTES.TRAINING, label: 'Training', iconName: 'IconBook' },
    { path: ROUTES.ASSETS, label: 'Assets', iconName: 'IconPackage' },
    { path: ROUTES.TIMESHEETS, label: 'Timesheets', iconName: 'IconClock' },
    { path: ROUTES.HELPDESK, label: 'Helpdesk', iconName: 'IconHelp' },
    { path: ROUTES.POLICIES, label: 'Policies', iconName: 'IconShield' },
    { path: ROUTES.DOCUMENTS, label: 'Documents', iconName: 'IconFolder' },
    { path: ROUTES.AUDIT_LOGS, label: 'Audit Logs', iconName: 'IconShield' },
    { path: ROUTES.SHIFTS, label: 'Shifts', iconName: 'IconClock' },
    { path: ROUTES.HOLIDAYS, label: 'Holidays', iconName: 'IconCalendar' },
  ],
  'HR Executive': [
    { path: ROUTES.DASHBOARD, label: 'Dashboard', iconName: 'IconDashboard' },
    { path: ROUTES.EMPLOYEES, label: 'Employees', iconName: 'IconUsers' },
    { path: ROUTES.DEPARTMENTS, label: 'Departments', iconName: 'IconFolder' },
    { path: ROUTES.DESIGNATIONS, label: 'Designations', iconName: 'IconBriefcase' },
    { path: ROUTES.ATTENDANCE, label: 'Attendance', iconName: 'IconCalendar' },
    { path: ROUTES.LEAVE, label: 'Leave', iconName: 'IconClock' },
    { path: ROUTES.REPORTS_ATTENDANCE, label: 'Attendance Reports', iconName: 'IconFileText' },
    { path: ROUTES.REPORTS_LEAVE, label: 'Leave Reports', iconName: 'IconFileText' },
    { path: ROUTES.REPORTS_RECRUITMENT, label: 'Recruitment Reports', iconName: 'IconFileText' },
    { path: ROUTES.JOBS, label: 'Job Openings', iconName: 'IconBriefcase' },
    { path: ROUTES.CANDIDATES, label: 'Candidates', iconName: 'IconUsers' },
    { path: ROUTES.INTERVIEWS, label: 'Interviews', iconName: 'IconCalendar' },
    { path: ROUTES.OFFER_LETTERS, label: 'Offer Letters', iconName: 'IconFileText' },
    { path: ROUTES.TRAINING, label: 'Training', iconName: 'IconBook' },
    { path: ROUTES.ASSETS, label: 'Assets', iconName: 'IconPackage' },
    { path: ROUTES.HELPDESK, label: 'Helpdesk', iconName: 'IconHelp' },
    { path: ROUTES.POLICIES, label: 'Policies', iconName: 'IconShield' },
    { path: ROUTES.DOCUMENTS, label: 'Documents', iconName: 'IconFolder' },
    { path: ROUTES.SHIFTS, label: 'Shifts', iconName: 'IconClock' },
    { path: ROUTES.HOLIDAYS, label: 'Holidays', iconName: 'IconCalendar' },
  ],
  'Manager': [
    { path: ROUTES.DASHBOARD, label: 'Dashboard', iconName: 'IconDashboard' },
    { path: ROUTES.EMPLOYEES, label: 'My Team', iconName: 'IconUsers' },
    { path: ROUTES.ATTENDANCE, label: 'Attendance', iconName: 'IconCalendar' },
    { path: ROUTES.LEAVE, label: 'Leave Approvals', iconName: 'IconClock' },
    { path: ROUTES.INTERVIEWS, label: 'Interviews', iconName: 'IconCalendar' },
    { path: ROUTES.REPORTS_ATTENDANCE, label: 'Attendance Reports', iconName: 'IconFileText' },
    { path: ROUTES.REPORTS_LEAVE, label: 'Leave Reports', iconName: 'IconFileText' },
    { path: ROUTES.PERFORMANCE, label: 'Performance', iconName: 'IconTrendingUp' },
    { path: ROUTES.TRAINING, label: 'Training', iconName: 'IconBook' },
    { path: ROUTES.TIMESHEETS, label: 'Timesheets', iconName: 'IconClock' },
    { path: ROUTES.ASSETS, label: 'Assets', iconName: 'IconPackage' },
    { path: ROUTES.HELPDESK, label: 'Helpdesk', iconName: 'IconHelp' },
    { path: ROUTES.POLICIES, label: 'Policies', iconName: 'IconShield' },
    { path: ROUTES.DOCUMENTS, label: 'Team Documents', iconName: 'IconFolder' },
    { path: ROUTES.SHIFTS, label: 'Shifts', iconName: 'IconClock' },
    { path: ROUTES.HOLIDAYS, label: 'Holidays', iconName: 'IconCalendar' },
  ],
  'Employee': [
    { path: ROUTES.DASHBOARD, label: 'Dashboard', iconName: 'IconDashboard' },
    { path: ROUTES.EMPLOYEE_ME, label: 'My Profile', iconName: 'IconUsers' },
    { path: ROUTES.ATTENDANCE, label: 'My Attendance', iconName: 'IconCalendar' },
    { path: ROUTES.LEAVE, label: 'My Leave', iconName: 'IconClock' },
    { path: ROUTES.REPORTS_ATTENDANCE, label: 'Attendance Reports', iconName: 'IconFileText' },
    { path: ROUTES.REPORTS_LEAVE, label: 'Leave Reports', iconName: 'IconFileText' },
    { path: ROUTES.PERFORMANCE, label: 'My Performance', iconName: 'IconTrendingUp' },
    { path: ROUTES.TRAINING, label: 'My Training', iconName: 'IconBook' },
    { path: ROUTES.ASSETS, label: 'My Assets', iconName: 'IconPackage' },
    { path: ROUTES.TIMESHEETS, label: 'My Timesheets', iconName: 'IconClock' },
    { path: ROUTES.HELPDESK, label: 'Helpdesk', iconName: 'IconHelp' },
    { path: ROUTES.POLICIES, label: 'Policies', iconName: 'IconShield' },
    { path: ROUTES.DOCUMENTS, label: 'My Documents', iconName: 'IconFolder' },
    { path: ROUTES.HOLIDAYS, label: 'Holidays', iconName: 'IconCalendar' },
  ],
  'Finance/Payroll Admin': [
    { path: ROUTES.DASHBOARD, label: 'Dashboard', iconName: 'IconDashboard' },
    { path: ROUTES.EMPLOYEES, label: 'Employees', iconName: 'IconUsers' },
    { path: ROUTES.PAYROLL, label: 'Payroll', iconName: 'IconDollar' },
    { path: ROUTES.TIMESHEETS, label: 'Timesheets', iconName: 'IconClock' },
    { path: ROUTES.AUDIT_LOGS, label: 'Audit Logs', iconName: 'IconShield' },
  ],
};

export const DASHBOARD_SECTIONS = {
  'Super Admin': [
    'System Overview', 'Employee Management', 'Payroll', 'Attendance', 'Administration'
  ],
  'HR Admin': [
    'Employee Management', 'Attendance', 'Leave', 'Recruitment', 'HR Operations'
  ],
  'HR Executive': [
    'Employees', 'Attendance', 'Leave', 'Recruitment'
  ],
  'Manager': [
    'My Team', 'Team Attendance', 'Leave Approvals', 'Performance'
  ],
  'Employee': [
    'My Attendance', 'My Leave', 'My Performance', 'My Training'
  ],
  'Finance/Payroll Admin': [
    'Payroll', 'Employees', 'Timesheets', 'Audit'
  ],
};
